
name: merian0818

on:
  push:
    branches: [ circleci-project-setup ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ circleci-project-setup ]
  schedule:
    - cron: '25 18 * * 6'

jobs:
    CodeScan:
        runs-on: ubuntu-latest
        steps:
            -   name: merian0818
                uses: actions/checkout@v2
            -   name: Cache files
                uses: actions/cache@v2
                with:
                    path: |
                        ~/.sonar
                    key: ${{ runner.os }}-sonar
                    restore-keys: ${{ runner.os }}-sonar
            -   name: Run Analysis
                uses: codescan-io/codescan-scanner-action@master
                with:
                    login: ${{ secrets.CODESCAN_AUTH_TOKEN }}
                    organization: ${{ ching16}}
                    projectKey: ${{ secrets.CODESCAN_PROJECT_KEY }}
            -   name: Upload SARIF file
                uses: github/codeql-action/upload-sarif@v1
                with:
                    sarif_file: codescan.sarif
